name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda create --name=myoccwlenv python=3.9
          /usr/share/miniconda/bin/activate myoccwlenv
          conda install -c lambouj -c conda-forge occwl
          python -m pip install --upgrade pip
          pip install nox
      - name: Lint/Test/Type
        run: |
          nox
